apiVersion: apps/v1
kind: Deployment
metadata:
  name: eoe-admission
  namespace: {{ .Release.Namespace }}
  labels:
    app: eoe-admission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eoe-admission
  template:
    metadata:
      labels:
        app: eoe-admission
    spec:
      containers:
      - name: eoe-admission-server
        image: registry.cn-shanghai.aliyuncs.com/viper/eoe
        imagePullPolicy: Always
        ports:
        - name: tls-port
          containerPort: 443
        volumeMounts:
        - name: eoe-admission-tls
          mountPath: /run/eoe/tls
          readOnly: true
      serviceAccountName: eoe-admission-controller-sa
      volumes:
      - name: eoe-admission-tls
        secret:
          secretName: eoe-admission