apiVersion: batch/v1
kind: Job
metadata:
  name: eoe-admission-create
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: eoe-admission-create
spec:
  {{- if .Capabilities.APIVersions.Has "batch/v1alpha1" }}
  ttlSecondsAfterFinished: 0
  {{- end }}
  template:
    metadata:
      name: eoe-admission-create
      labels:
        app: eoe-admission-create
    spec:
      containers:
        - name: create
          image: m.daocloud.io/k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.0
          imagePullPolicy: Always
          args:
            - create
            - --host=eoe-admission,eoe-admission.{{ .Release.Namespace }}.svc
            - --namespace={{ .Release.Namespace }}
            - --secret-name=eoe-admission
            - --key-name=tls.key
            - --cert-name=tls.crt
      restartPolicy: OnFailure
      serviceAccountName: eoe-admission
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
