apiVersion: batch/v1
kind: Job
metadata:
  name: eoe-admission-patch
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: eoe-admission-patch
spec:
  {{- if .Capabilities.APIVersions.Has "batch/v1alpha1" }}
  ttlSecondsAfterFinished: 0
  {{- end }}
  template:
    metadata:
      name: eoe-admission-patch
      labels:
        app: eoe-admission-patch
    spec:
      containers:
        - name: patch
          image: jettech/kube-webhook-certgen:v1.5.2
          imagePullPolicy: Always
          args:
            - patch
            - --webhook-name=eoe-admission
            - --namespace={{ .Release.Namespace }}
            - --secret-name=eoe-admission
            - --patch-failure-policy=Fail
      restartPolicy: OnFailure
      serviceAccountName: eoe-admission
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
