apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eoe-admission
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: eoe-admission
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eoe-admission
subjects:
  - kind: ServiceAccount
    name: eoe-admission
    namespace: {{ .Release.Namespace }}